{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "460624a5",
   "metadata": {
    "_execution_state": "idle",
    "_uuid": "051d70d956493feee0c6d64651c6a088724dca2a",
    "execution": {
     "iopub.execute_input": "2025-09-18T15:02:11.143576Z",
     "iopub.status.busy": "2025-09-18T15:02:11.140986Z",
     "iopub.status.idle": "2025-09-18T15:02:25.021269Z",
     "shell.execute_reply": "2025-09-18T15:02:25.019287Z"
    },
    "papermill": {
     "duration": 13.88933,
     "end_time": "2025-09-18T15:02:25.025025",
     "exception": false,
     "start_time": "2025-09-18T15:02:11.135695",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [],
      "text/latex": [],
      "text/markdown": [],
      "text/plain": [
       "character(0)"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      " Total de columnas borradas 0 \n",
      "\n"
     ]
    }
   ],
   "source": [
    "suppressMessages( {\n",
    "  #install.packages(\"lightgbm\", quiet = TRUE)\n",
    "  library(lightgbm)\n",
    "  library(catboost)\n",
    "  library(xgboost)\n",
    "  library(Metrics)\n",
    "  library(recipes)\n",
    "  library(modelr)\n",
    "  library(caret)\n",
    "  library(data.table)\n",
    "  library(tidyverse)\n",
    "  library(MLmetrics)\n",
    "  library(ModelMetrics)\n",
    "  library(tidyverse)\n",
    "})\n",
    "\n",
    "free <- function() invisible(gc())\n",
    "calcMode <- function(x) {\n",
    "  x <- x[!is.na(x)]\n",
    "  ux <- unique(x)\n",
    "  ux[which.max(tabulate(match(x, ux)))]\n",
    "}\n",
    "\n",
    "avgAUC <- function(real, pred){\n",
    "  avgRes <- c()\n",
    "  real <- as.matrix(real)\n",
    "  for(iPred in 1:ncol(real)){\n",
    "    nameCol <- names(real)[iPred]\n",
    "    avgRes <- c(avgRes,auc(real[,iPred], pred[,iPred]))\n",
    "  }\n",
    "  return(mean(avgRes))\n",
    "}\n",
    "\n",
    "# Read files\n",
    "PATH <- \"/kaggle/input/playground-series-s5e9/\"\n",
    "dt <- fread(paste0(PATH, \"train.csv\"))\n",
    "#dt2 <- fread(\"/kaggle/input/loan-approval-prediction/credit_risk_dataset.csv\")\n",
    "#dt2 <- cbind(id = 1:nrow(dt2),dt2)\n",
    "#dt <- rbind(dt, dt2)\n",
    "#rm(dt2)\n",
    "\n",
    "dtest <- fread(paste0(PATH, \"test.csv\"))\n",
    "sub <- fread(paste0(PATH,\"sample_submission.csv\"))\n",
    "subTemp <- sub[,2]\n",
    "\n",
    "# Identify target\n",
    "target <- names(dt)[!names(dt) %in% names(dtest)] \n",
    "Y <- dt[,..target]\n",
    "Y <- apply(Y, 1, max)\n",
    "dt[,(target):=NULL]\n",
    "\n",
    "# Merge both sources train and test\n",
    "dtTotal <- rbind(data.table(fuente = \"train\",dt),\n",
    "                 data.table(fuente = \"test\",dtest))\n",
    "\n",
    "####################################\n",
    "### Elimino variables duplicadas ###\n",
    "####################################\n",
    "colsDuplicated <- names(dtTotal)[duplicated(as.list(dtTotal))]\n",
    "colsDuplicated\n",
    "if(length(colsDuplicated)>0) {\n",
    "  dtTotal[,(colsDuplicated):= NULL]\n",
    "}\n",
    "\n",
    "####################################\n",
    "### Elimino variables %Nulls     ###\n",
    "####################################\n",
    "fCols <- names(dtTotal)\n",
    "if(1==1){\n",
    "  muchosNulos <- names(dtTotal)[colMeans(is.na(dtTotal))>=0.80]\n",
    "  muchosNulos\n",
    "  if(length(muchosNulos)>0) {\n",
    "    dtTotal[, c(muchosNulos):=NULL]\n",
    "  }\n",
    "}\n",
    "\n",
    "####################################\n",
    "### Elimino variables one value  ###\n",
    "####################################\n",
    "fCols <- names(dtTotal)\n",
    "nCategories <- dtTotal[, lapply(.SD, function(x) {uniqueN(x)} ), .SDcols = fCols]\n",
    "feaUnicoValor <- fCols[nCategories==1]\n",
    "if(length(feaUnicoValor)>0) {\n",
    "  dtTotal[, c(feaUnicoValor):=NULL]\n",
    "}\n",
    "#########################################\n",
    "## Agrego cuantas filas nulas por feature\n",
    "#########################################\n",
    "if(sum(colSums(is.na(dtTotal))>0)>0){\n",
    "  dtTotal$FilasNulas <- rowSums(is.na(dtTotal))  \n",
    "}\n",
    "\n",
    "###################################\n",
    "###### Features tipo caracter #####\n",
    "###################################\n",
    "fCols <- names(dtTotal)[3:ncol(dtTotal)]\n",
    "fChar <- dtTotal[, lapply(.SD, function(x) {is.character(x)} ), .SDcols = fCols]\n",
    "fColsChr <- fCols[fChar==TRUE]\n",
    "if(length(fColsChr)>0){\n",
    "  dtTotal[, (fColsChr) := lapply(.SD, function(x) { as.integer(factor(x)) } ), .SDcols = fColsChr] \n",
    "}\n",
    "\n",
    "###################################\n",
    "### Features con poca variación  ##\n",
    "###################################\n",
    "ColsTotal <- names(dtTotal[,3:ncol(dtTotal)])\n",
    "iColsBorradas <- 0\n",
    "for(c in ColsTotal){\n",
    "  moda <- apply(dtTotal[,..c],2,calcMode)\n",
    "  prcRepetido <- mean(dtTotal[,..c]==moda, na.rm=T)\n",
    "  if(prcRepetido>= 0.999){\n",
    "    cat(paste(\"La variable \",c,\" tiene un mismo valor que se repite \", prcRepetido, \"... va a ser borrada \\n\"))\n",
    "    dtTotal[,c(c):=NULL]\n",
    "    iColsBorradas <- iColsBorradas + 1\n",
    "  }\n",
    "}\n",
    "cat(paste0(\"\\n Total de columnas borradas \", iColsBorradas),\"\\n\\n\")\n",
    "##########################\n",
    "\n",
    "###################################\n",
    "### Frec Encoding para var CAT  ###\n",
    "###################################\n",
    "if(1==1){\n",
    "  fCols <- names(dtTotal)[3:ncol(dtTotal)]\n",
    "  nCategories <- dtTotal[, lapply(.SD, function(x) {uniqueN(x)} ), .SDcols = fCols]\n",
    "  feaCAT <- fCols[nCategories<=15]\n",
    "  \n",
    "  for(c in feaCAT){\n",
    "    #cat(c)\n",
    "    #med <- mean(dtTotal[,..c], na.rm = T)\n",
    "    grp <- dtTotal[,..c][, .N,c]\n",
    "    dtTotal[grp, paste0(c,\"_FreqEnc\") := N ,on = c]\n",
    "  }\n",
    "}\n",
    "\n",
    "##############################\n",
    "### Eliminar correlacionados\n",
    "if(1==2){\n",
    "  correlationMatrix <- cor(dtTotal[,3:ncol(dtTotal)])\n",
    "  remove_cols <-\n",
    "    findCorrelation(x = correlationMatrix, cutoff = 0.999, verbose = FALSE, names=TRUE)\n",
    "  if(length(remove_cols)>0){\n",
    "    dtTotal[,c(remove_cols):=NULL] \n",
    "  }\n",
    "}\n",
    "##############################\n",
    "## outliers\n",
    "##############################\n",
    "if(1==2){\n",
    "    fCols <- names(dtTotal)[3:ncol(dtTotal)]\n",
    "    q1Features <- apply(dtTotal[,..fCols], 2, function(x) {quantile(x,0.25)})\n",
    "    q3Features <- apply(dtTotal[,..fCols], 2, function(x) {quantile(x,0.75)})\n",
    "    IQRFeatures <- q3Features - q1Features\n",
    "    OutliersLeft <- q1Features - IQRFeatures*1.5\n",
    "    OutliersRight <- q3Features + IQRFeatures*1.5\n",
    "    nOutliersLeft <- apply(dtTotal[,..fCols], 1, function(x) { sum(x <= OutliersLeft)}) \n",
    "    nOutliersRight <- apply(dtTotal[,..fCols], 1, function(x) { sum(x >= OutliersRight)})\n",
    "    nOutliers <- nOutliersLeft + nOutliersRight\n",
    "    #dtTotal[,nOutliersLeft := nOutliersLeft]\n",
    "    #dtTotal[,nOutliersRight := nOutliersRight]\n",
    "    dtTotal[,nOutliers := nOutliers]    \n",
    "}\n",
    "\n",
    "###################################\n",
    "####### Tratamiento Nulos   #######\n",
    "###################################\n",
    "if(1==1){\n",
    "  ColsNulls <- names(dtTotal)[colSums( is.na(dtTotal))>0]\n",
    "  for(c in ColsNulls){\n",
    "    #cat(c)\n",
    "    #med <- mean(dtTotal[,..c], na.rm = T)\n",
    "    #med <- apply(dtTotal[,..c],2,mean,na.rm=T)\n",
    "    med <- apply(dtTotal[,..c],2,median,na.rm=T)\n",
    "    #med <- 0\n",
    "    #med <- apply(dtTotal[,..c],2,median,na.rm=T)\n",
    "    dtTotal[, (c) := lapply(.SD, function(x) { ifelse(is.na(x),med,x)  } ), .SDcols = c]\n",
    "  }\n",
    "}\n",
    "\n",
    "####################################\n",
    "### Feature Engineering ###\n",
    "####################################\n",
    "#dtTotal[,loan_to_income := (loan_amnt/person_income) - loan_percent_income]\n",
    "\n",
    "\n",
    "### divido ambos dataset de nuevo\n",
    "dt <- dtTotal[fuente == 'train', ]\n",
    "dtest <- dtTotal[fuente == 'test', ]\n",
    "\n",
    "rec <- dt %>%\n",
    "    recipe(~ .) %>%\n",
    "    step_rm(id) %>% \n",
    "    step_rm(fuente) %>% \n",
    "    step_corr(all_numeric(), threshold = .98) %>% \n",
    "    #step_BoxCox(all_numeric()) %>%\n",
    "    step_normalize(all_numeric()) %>%\n",
    "    prep()\n",
    "\n",
    "dt <- juice(rec, composition = \"data.frame\")\n",
    "dtest <- bake(rec, dtest, composition = \"data.frame\")\n",
    "setDT(dt)\n",
    "setDT(dtest)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "cb569cf4",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2025-09-18T15:02:25.099155Z",
     "iopub.status.busy": "2025-09-18T15:02:25.034774Z",
     "iopub.status.idle": "2025-09-18T18:14:18.494737Z",
     "shell.execute_reply": "2025-09-18T18:14:18.492646Z"
    },
    "papermill": {
     "duration": 11513.47033,
     "end_time": "2025-09-18T18:14:18.498244",
     "exception": false,
     "start_time": "2025-09-18T15:02:25.027914",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      " LGBM Fold  1 - 10 \n",
      "\n",
      " XGB Best score: 26.43613 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.43613\n",
      "\n",
      " XGBoost  26.43613 AvgMetrics 26.43613 \n",
      "\n",
      " LGBM Fold  2 - 10 \n",
      "\n",
      " XGB Best score: 26.45179 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.45179\n",
      "\n",
      " XGBoost  26.45179 AvgMetrics 26.44396 \n",
      "\n",
      " LGBM Fold  3 - 10 \n",
      "\n",
      " XGB Best score: 26.35143 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.35143\n",
      "\n",
      " XGBoost  26.35143 AvgMetrics 26.41312 \n",
      "\n",
      " LGBM Fold  4 - 10 \n",
      "\n",
      " XGB Best score: 26.54601 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.54601\n",
      "\n",
      " XGBoost  26.54601 AvgMetrics 26.44634 \n",
      "\n",
      " LGBM Fold  5 - 10 \n",
      "\n",
      " XGB Best score: 26.36858 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.36858\n",
      "\n",
      " XGBoost  26.36858 AvgMetrics 26.43079 \n",
      "\n",
      " LGBM Fold  6 - 10 \n",
      "\n",
      " XGB Best score: 26.51343 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.51343\n",
      "\n",
      " XGBoost  26.51343 AvgMetrics 26.44456 \n",
      "\n",
      " LGBM Fold  7 - 10 \n",
      "\n",
      " XGB Best score: 26.61011 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.61011\n",
      "\n",
      " XGBoost  26.61011 AvgMetrics 26.46821 \n",
      "\n",
      " LGBM Fold  8 - 10 \n",
      "\n",
      " XGB Best score: 26.41435 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.41435\n",
      "\n",
      " XGBoost  26.41435 AvgMetrics 26.46148 \n",
      "\n",
      " LGBM Fold  9 - 10 \n",
      "\n",
      " XGB Best score: 26.54041 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.54041\n",
      "\n",
      " XGBoost  26.54041 AvgMetrics 26.47025 \n",
      "\n",
      " LGBM Fold  10 - 10 \n",
      "\n",
      " XGB Best score: 26.50009 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.50009\n",
      "\n",
      " XGBoost  26.50009 AvgMetrics 26.47323 \n",
      "\n",
      " LGBM Fold  1 - 10 \n",
      "\n",
      " XGB Best score: 26.45517 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.45517\n",
      "\n",
      " XGBoost  26.45517 AvgMetrics 26.45517 \n",
      "\n",
      " LGBM Fold  2 - 10 \n",
      "\n",
      " XGB Best score: 26.54332 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.54332\n",
      "\n",
      " XGBoost  26.54332 AvgMetrics 26.49925 \n",
      "\n",
      " LGBM Fold  3 - 10 \n",
      "\n",
      " XGB Best score: 26.45601 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.45601\n",
      "\n",
      " XGBoost  26.45601 AvgMetrics 26.48483 \n",
      "\n",
      " LGBM Fold  4 - 10 \n",
      "\n",
      " XGB Best score: 26.34016 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.34016\n",
      "\n",
      " XGBoost  26.34016 AvgMetrics 26.44867 \n",
      "\n",
      " LGBM Fold  5 - 10 \n",
      "\n",
      " XGB Best score: 26.42921 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.42921\n",
      "\n",
      " XGBoost  26.42921 AvgMetrics 26.44477 \n",
      "\n",
      " LGBM Fold  6 - 10 \n",
      "\n",
      " XGB Best score: 26.54167 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.54167\n",
      "\n",
      " XGBoost  26.54167 AvgMetrics 26.46092 \n",
      "\n",
      " LGBM Fold  7 - 10 \n",
      "\n",
      " XGB Best score: 26.44778 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.44778\n",
      "\n",
      " XGBoost  26.44778 AvgMetrics 26.45905 \n",
      "\n",
      " LGBM Fold  8 - 10 \n",
      "\n",
      " XGB Best score: 26.48898 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.48898\n",
      "\n",
      " XGBoost  26.48898 AvgMetrics 26.46279 \n",
      "\n",
      " LGBM Fold  9 - 10 \n",
      "\n",
      " XGB Best score: 26.54381 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.54381\n",
      "\n",
      " XGBoost  26.54381 AvgMetrics 26.47179 \n",
      "\n",
      " LGBM Fold  10 - 10 \n",
      "\n",
      " XGB Best score: 26.47249 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.47249\n",
      "\n",
      " XGBoost  26.47249 AvgMetrics 26.47186 \n",
      "\n",
      " LGBM Fold  1 - 10 \n",
      "\n",
      " XGB Best score: 26.4246 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.4246\n",
      "\n",
      " XGBoost  26.4246 AvgMetrics 26.4246 \n",
      "\n",
      " LGBM Fold  2 - 10 \n",
      "\n",
      " XGB Best score: 26.47269 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.47269\n",
      "\n",
      " XGBoost  26.47269 AvgMetrics 26.44864 \n",
      "\n",
      " LGBM Fold  3 - 10 \n",
      "\n",
      " XGB Best score: 26.49295 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.49295\n",
      "\n",
      " XGBoost  26.49295 AvgMetrics 26.46341 \n",
      "\n",
      " LGBM Fold  4 - 10 \n",
      "\n",
      " XGB Best score: 26.46241 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.46241\n",
      "\n",
      " XGBoost  26.46241 AvgMetrics 26.46316 \n",
      "\n",
      " LGBM Fold  5 - 10 \n",
      "\n",
      " XGB Best score: 26.48582 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.48582\n",
      "\n",
      " XGBoost  26.48582 AvgMetrics 26.46769 \n",
      "\n",
      " LGBM Fold  6 - 10 \n",
      "\n",
      " XGB Best score: 26.59266 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.59266\n",
      "\n",
      " XGBoost  26.59266 AvgMetrics 26.48852 \n",
      "\n",
      " LGBM Fold  7 - 10 \n",
      "\n",
      " XGB Best score: 26.43195 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.43195\n",
      "\n",
      " XGBoost  26.43195 AvgMetrics 26.48044 \n",
      "\n",
      " LGBM Fold  8 - 10 \n",
      "\n",
      " XGB Best score: 26.33025 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.33025\n",
      "\n",
      " XGBoost  26.33025 AvgMetrics 26.46167 \n",
      "\n",
      " LGBM Fold  9 - 10 \n",
      "\n",
      " XGB Best score: 26.51401 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.51401\n",
      "\n",
      " XGBoost  26.51401 AvgMetrics 26.46748 \n",
      "\n",
      " LGBM Fold  10 - 10 \n",
      "\n",
      " XGB Best score: 26.52177 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.52177\n",
      "\n",
      " XGBoost  26.52177 AvgMetrics 26.47291 \n",
      "\n",
      " LGBM Fold  1 - 10 \n",
      "\n",
      " XGB Best score: 26.56919 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.56919\n",
      "\n",
      " XGBoost  26.56919 AvgMetrics 26.56919 \n",
      "\n",
      " LGBM Fold  2 - 10 \n",
      "\n",
      " XGB Best score: 26.52515 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.52515\n",
      "\n",
      " XGBoost  26.52515 AvgMetrics 26.54717 \n",
      "\n",
      " LGBM Fold  3 - 10 \n",
      "\n",
      " XGB Best score: 26.4564 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.4564\n",
      "\n",
      " XGBoost  26.4564 AvgMetrics 26.51691 \n",
      "\n",
      " LGBM Fold  4 - 10 \n",
      "\n",
      " XGB Best score: 26.31414 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.31414\n",
      "\n",
      " XGBoost  26.31414 AvgMetrics 26.46622 \n",
      "\n",
      " LGBM Fold  5 - 10 \n",
      "\n",
      " XGB Best score: 26.51907 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.51907\n",
      "\n",
      " XGBoost  26.51907 AvgMetrics 26.47679 \n",
      "\n",
      " LGBM Fold  6 - 10 \n",
      "\n",
      " XGB Best score: 26.37329 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.37329\n",
      "\n",
      " XGBoost  26.37329 AvgMetrics 26.45954 \n",
      "\n",
      " LGBM Fold  7 - 10 \n",
      "\n",
      " XGB Best score: 26.47044 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.47044\n",
      "\n",
      " XGBoost  26.47044 AvgMetrics 26.4611 \n",
      "\n",
      " LGBM Fold  8 - 10 \n",
      "\n",
      " XGB Best score: 26.45207 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.45207\n",
      "\n",
      " XGBoost  26.45207 AvgMetrics 26.45997 \n",
      "\n",
      " LGBM Fold  9 - 10 \n",
      "\n",
      " XGB Best score: 26.52701 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.52701\n",
      "\n",
      " XGBoost  26.52701 AvgMetrics 26.46742 \n",
      "\n",
      " LGBM Fold  10 - 10 \n",
      "\n",
      " XGB Best score: 26.52783 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.52783\n",
      "\n",
      " XGBoost  26.52783 AvgMetrics 26.47346 \n",
      "\n",
      " LGBM Fold  1 - 10 \n",
      "\n",
      " XGB Best score: 26.55341 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.55341\n",
      "\n",
      " XGBoost  26.55341 AvgMetrics 26.55341 \n",
      "\n",
      " LGBM Fold  2 - 10 \n",
      "\n",
      " XGB Best score: 26.4396 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.4396\n",
      "\n",
      " XGBoost  26.4396 AvgMetrics 26.49651 \n",
      "\n",
      " LGBM Fold  3 - 10 \n",
      "\n",
      " XGB Best score: 26.38061 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.38061\n",
      "\n",
      " XGBoost  26.38061 AvgMetrics 26.45787 \n",
      "\n",
      " LGBM Fold  4 - 10 \n",
      "\n",
      " XGB Best score: 26.55295 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.55295\n",
      "\n",
      " XGBoost  26.55295 AvgMetrics 26.48164 \n",
      "\n",
      " LGBM Fold  5 - 10 \n",
      "\n",
      " XGB Best score: 26.52735 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.52735\n",
      "\n",
      " XGBoost  26.52735 AvgMetrics 26.49079 \n",
      "\n",
      " LGBM Fold  6 - 10 \n",
      "\n",
      " XGB Best score: 26.51824 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.51824\n",
      "\n",
      " XGBoost  26.51824 AvgMetrics 26.49536 \n",
      "\n",
      " LGBM Fold  7 - 10 \n",
      "\n",
      " XGB Best score: 26.3859 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.3859\n",
      "\n",
      " XGBoost  26.3859 AvgMetrics 26.47972 \n",
      "\n",
      " LGBM Fold  8 - 10 \n",
      "\n",
      " XGB Best score: 26.49761 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.49761\n",
      "\n",
      " XGBoost  26.49761 AvgMetrics 26.48196 \n",
      "\n",
      " LGBM Fold  9 - 10 \n",
      "\n",
      " XGB Best score: 26.42557 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.42557\n",
      "\n",
      " XGBoost  26.42557 AvgMetrics 26.4757 \n",
      "\n",
      " LGBM Fold  10 - 10 \n",
      "\n",
      " XGB Best score: 26.4434 at 500 iteration\n",
      " XGBoost \n",
      "[1] 26.4434\n",
      "\n",
      " XGBoost  26.4434 AvgMetrics 26.47247 \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "metric XGB 26.47247 \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1] 26.47335\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1] 26.47193\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1] 26.47299\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1] 26.47356\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1] 26.47254\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Metric mean  26.47287"
     ]
    }
   ],
   "source": [
    "####################################\n",
    "# Paso 2 Prediccion\n",
    "####################################\n",
    "oof <- data.frame(target = Y)\n",
    "#dt[,c(\"fuente\", \"id\"):=NULL]\n",
    "#dtest[,c(\"fuente\", \"id\"):=NULL]\n",
    "subSeeds <- sub\n",
    "setDF(subSeeds)\n",
    "subSeeds[,-1] <- 0\n",
    "free()\n",
    "\n",
    "scores <- c()\n",
    "#SEEDS <- c(2503)\n",
    "SEEDS <- c(1975, 2000, 2503,1511,2604)\n",
    "for (s in SEEDS) {\n",
    "  \n",
    "    set.seed(s)\n",
    "    nameSeed <- paste0(\"Seed_\",s)\n",
    "    subSeeds[, nameSeed] <- 0\n",
    "    kfolds = 10\n",
    "    #set.seed(0)\n",
    "    folds <- createFolds(Y, k = kfolds, list = FALSE)\n",
    "    pred <- rep(0,nrow(sub))\n",
    "    predCB_Total <- pred\n",
    "    predLGBM_Total <- pred\n",
    "    predXGB_Total <- pred\n",
    "\n",
    "    aucCBTotal <- 0\n",
    "    aucLGBMTotal <- 0\n",
    "    aucXGBTotal <- 0\n",
    "    aucTotal <- 0\n",
    "    auc_LGBM <- 0\n",
    "\n",
    "    dtMatrix <- data.matrix(dt)\n",
    "    dtestMatrix <- data.matrix(dtest)\n",
    "    #rm(dt, dtest); free()\n",
    "    iFold <- 1\n",
    "\n",
    "    for (iFold in 1:kfolds)\n",
    "      #for (iFold in 1:1)\n",
    "    {\n",
    "      cat(\"\\n LGBM Fold \",iFold, \"-\", kfolds, \"\\n\")\n",
    "\n",
    "      idx <- which(folds!=iFold)\n",
    "\n",
    "      ############################\n",
    "      ######## XGBOOST ##########\n",
    "      ############################  \n",
    "\n",
    "      train_matrix <- xgb.DMatrix(data = dtMatrix[idx, ], label = Y[idx])\n",
    "      test_matrix <- xgb.DMatrix(data =  dtMatrix[-idx,], label = Y[-idx])\n",
    "      watchlist <- list(train = train_matrix, test = test_matrix)\n",
    "\n",
    "      XGB_model <- xgb.train(#params = xgb_params,\n",
    "        nrounds = 500 #10000 #30000\n",
    "        , data = train_matrix\n",
    "        , watchlist = watchlist\n",
    "        , objective = 'reg:squarederror'\n",
    "        , eta = 0.01 #0.01     \n",
    "        #, seed = s\n",
    "        , eval_metric = 'rmse'\n",
    "        , early_stopping_rounds=1000  ##400\n",
    "        , maximize=FALSE\n",
    "        , print_every_n = 100\n",
    "        , verbose = F\n",
    "        , nthread = 4\n",
    "        ,booster = \"gbtree\") #--> Best score: 0.896855 at 1489 iteration\n",
    "      cat(\"\\n XGB Best score:\", XGB_model$best_score, \"at\", XGB_model$best_iter, \"iteration\")  \n",
    "\n",
    "      testXGB <- predict(XGB_model, dtMatrix[-idx, ])\n",
    "      #oof[-idx, \"XGB\"] <- testXGB\n",
    "      nameSeed <- paste0(\"XGB_Seed_\",s)\n",
    "      oof[-idx, nameSeed] <- testXGB\n",
    "\n",
    "      AUC_XGB <- rmse(Y[-idx], testXGB)\n",
    "      aucXGBTotal <- aucXGBTotal + AUC_XGB\n",
    "      cat(\"\\n XGBoost \\n\")\n",
    "      print(AUC_XGB)\n",
    "      cat(\"\\n XGBoost \", AUC_XGB, \"AvgMetrics\", aucXGBTotal/iFold, \"\\n\")\n",
    "\n",
    "      predXGB <- predict(XGB_model, dtestMatrix)\n",
    "      predXGB_Total <- predXGB_Total + predXGB\n",
    "\n",
    "      subTemp[, paste0(\"Seed_s\",s,\"Fold_\",iFold)] <- predXGB\n",
    "      nameSeed <- paste0(\"Seed_\",s)\n",
    "      subSeeds[, nameSeed] <- subSeeds[, nameSeed] + predXGB/ kfolds \n",
    "\n",
    "      ############################\n",
    "      ############################\n",
    "    }\n",
    "}\n",
    "\n",
    "predXGB_Total <- predXGB_Total/kfolds\n",
    "cat(\"metric XGB\", aucXGBTotal/kfolds,\"\\n\")\n",
    "\n",
    "sub[,2]  <- apply(subTemp[,2:ncol(subTemp)],1,mean)\n",
    "fwrite(sub, \"subXGBFit_v1.csv\")\n",
    "\n",
    "sub[,2]  <- apply(subTemp[,2:ncol(subTemp)],1,median)\n",
    "fwrite(sub, \"subXGBFitMedian_v1.csv\")\n",
    "\n",
    "fwrite(subTemp, \"subFoldXGBFit_v1.csv\")\n",
    "fwrite(oof, \"OOF_XGBFit_v1.csv\")\n",
    "\n",
    "fwrite(subSeeds,\"subSeedsXGB_v1.csv\") #-- 3 Envío\n",
    "\n",
    "#print(auc(oof$target, oof$CB))\n",
    "print(rmse(oof$target, oof$XGB_Seed_1975))\n",
    "print(rmse(oof$target, oof$XGB_Seed_2000))\n",
    "print(rmse(oof$target, oof$XGB_Seed_2503))\n",
    "print(rmse(oof$target, oof$XGB_Seed_1511))\n",
    "print(rmse(oof$target, oof$XGB_Seed_2604))\n",
    "\n",
    "aucMean <-( (rmse(oof[,1], oof[,2]) + rmse(oof[,1], oof[,3]) + rmse(oof[,1], oof[,4]) + \n",
    "            rmse(oof[,1], oof[,5]) + rmse(oof[,1], oof[,6]))/5)\n",
    "cat(\"Metric mean \", aucMean)"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [
    {
     "databundleVersionId": 13345277,
     "sourceId": 91720,
     "sourceType": "competition"
    }
   ],
   "dockerImageVersionId": 30749,
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "r",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "4.4.0"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 11533.146476,
   "end_time": "2025-09-18T18:14:20.062802",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2025-09-18T15:02:06.916326",
   "version": "2.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
